"""
AST builder visitor for FORMULA parser.

This module converts ANTLR4 parse trees into FORMULA AST nodes.
"""

from typing import Optional, List, Any, Union
from antlr4 import ParserRuleContext

from ..parser.FormulaParser import FormulaParser
from ..parser.FormulaParserVisitor import FormulaParserVisitor
from ..api.nodes import (
    Node,
    Span,
    ProgramName,
    Program,
    Domain,
    Model,
    Transform,
    Rule,
    Id,
    Cnst,
    FuncTerm,
    ModRef,
    Config,
    Setting,
)
from ..common import (
    Rational,
    ComposeKind,
    OpKind,
    RelKind,
)


class ParseResult:
    """Result of parsing a FORMULA program."""

    def __init__(self, program: Optional[Program] = None):
        """
        Create a parse result.

        Args:
            program: The parsed program (if successful)
        """
        self.program = program
        self.succeeded = True
        self.flags: List[str] = []  # Error and warning messages

    def add_flag(self, message: str):
        """Add an error or warning message."""
        self.flags.append(message)
        self.succeeded = False


class ASTBuilder(FormulaParserVisitor):
    """
    Visitor that builds FORMULA AST from ANTLR4 parse trees.

    This visitor walks the parse tree generated by FormulaParser and
    constructs the corresponding AST nodes.
    """

    def __init__(self):
        """Create an AST builder."""
        self.parse_result: Optional[ParseResult] = None
        self.current_module: Optional[Node] = None

        # State for building terms
        self.arg_stack: List[Node] = []

        # State for building rules and contracts
        self.current_rule: Optional[Rule] = None

        # State for building type declarations
        self.current_type_decl: Optional[Node] = None
        self.current_type_decl_name: Optional[str] = None

        # State for module references
        self.current_mod_ref: Optional[ModRef] = None

        # State for sentence configs
        self.current_sent_conf: Optional[Config] = None

    def parse_program(self, text: str, program_name: Optional[str] = None) -> ParseResult:
        """
        Parse a FORMULA program from text.

        Args:
            text: The program text
            program_name: Optional program name

        Returns:
            ParseResult with the parsed program
        """
        from antlr4 import InputStream, CommonTokenStream

        from ..parser.FormulaLexer import FormulaLexer
        from ..parser.FormulaParser import FormulaParser

        # Create the lexer and parser
        input_stream = InputStream(text)
        lexer = FormulaLexer(input_stream)
        token_stream = CommonTokenStream(lexer)
        parser = FormulaParser(token_stream)

        # Initialize parse result
        prog_name = program_name or "unknown"
        name = ProgramName(name=prog_name, uri=f"formula://{prog_name}")
        self.parse_result = ParseResult(Program(Span(0, 0, 0, 0, name), name))

        # Parse and visit
        try:
            tree = parser.program()
            self.visit(tree)
        except Exception as e:
            self.parse_result.add_flag(f"Parse error: {e}")

        return self.parse_result

    def to_span(self, token_or_ctx: Union[Any, ParserRuleContext]) -> Span:
        """
        Convert an ANTLR token or context to a Span.

        Args:
            token_or_ctx: ANTLR token or parser rule context

        Returns:
            Span representing the source location
        """
        if isinstance(token_or_ctx, ParserRuleContext):
            start = token_or_ctx.start
            stop = token_or_ctx.stop
        else:
            start = stop = token_or_ctx

        program_name = self.parse_result.program.name if self.parse_result else None

        return Span(
            start_line=start.line,
            start_col=start.column,
            end_line=stop.line,
            end_col=stop.column + len(stop.text) - 1,
            program=program_name,
        )

    # ============================================================================
    # Program and module visitors
    # ============================================================================

    def visitProgram(self, ctx: FormulaParser.ProgramContext):
        """Visit a program (root of the parse tree)."""
        if ctx.config():
            self.visit(ctx.config())

        if ctx.moduleList():
            self.visit(ctx.moduleList())

        return None

    def visitModuleList(self, ctx: FormulaParser.ModuleListContext):
        """Visit a list of modules."""
        # module() returns a list of all module contexts
        for module_ctx in ctx.module():
            self.visit(module_ctx)

        return None

    def visitModule(self, ctx: FormulaParser.ModuleContext):
        """Visit a module (domain, model, transform, etc.)."""
        if ctx.domain():
            self.visit(ctx.domain())
        elif ctx.model():
            self.visit(ctx.model())
        elif ctx.transform():
            self.visit(ctx.transform())
        # TODO: Add machine, tsystem

        return None

    # ============================================================================
    # Domain visitors
    # ============================================================================

    def visitDomain(self, ctx: FormulaParser.DomainContext):
        """Visit a domain declaration."""
        # Visit the signature to extract name and composition kind
        self.visit(ctx.domainSigConfig())

        # Visit sentences (type decls, rules, etc.)
        if ctx.domSentences():
            self.visit(ctx.domSentences())

        self._end_module()
        return None

    def visitDomainSigConfig(self, ctx: FormulaParser.DomainSigConfigContext):
        """Visit domain signature and config."""
        if ctx.config():
            # TODO: Handle config
            pass

        self.visit(ctx.domainSig())
        return None

    def visitDomainSig(self, ctx: FormulaParser.DomainSigContext):
        """Visit domain signature."""
        name = ctx.BAREID().getText()

        # Determine composition kind
        compose_kind = ComposeKind.NONE
        if ctx.EXTENDS():
            compose_kind = ComposeKind.EXTENDS
        elif ctx.INCLUDES():
            compose_kind = ComposeKind.INCLUDES

        # Create domain node
        span = self.to_span(ctx)
        domain = Domain(span, name, compose_kind)
        self.parse_result.program.add_module(domain)
        self.current_module = domain

        # Visit compositions
        if ctx.modRefs():
            self.visit(ctx.modRefs())

        return None

    def visitDomSentences(self, ctx: FormulaParser.DomSentencesContext):
        """Visit domain sentences."""
        # Visit config if present
        self.visit(ctx.domSentenceConfig())

        # Continue with rest of sentences
        if ctx.domSentences():
            self.visit(ctx.domSentences())

        return None

    def visitDomSentenceConfig(self, ctx: FormulaParser.DomSentenceConfigContext):
        """Visit domain sentence with config."""
        if ctx.sentenceConfig():
            self.visit(ctx.sentenceConfig())

        if ctx.domSentence():
            self.visit(ctx.domSentence())

        return None

    def visitDomSentence(self, ctx: FormulaParser.DomSentenceContext):
        """Visit a domain sentence (rule or type declaration)."""
        if ctx.rule():
            self.visit(ctx.rule())
        # TODO: Add other sentence types (conDecl, mapDecl, etc.)

        return None

    # ============================================================================
    # Rule visitors
    # ============================================================================

    def visitRuleItem(self, ctx: FormulaParser.RuleItemContext):
        """Visit a rule or fact."""
        # TODO: Implement rule building
        # For now, create a minimal rule
        span = self.to_span(ctx)
        rule = Rule(span)

        if isinstance(self.current_module, Domain):
            self.current_module.add_rule(rule)

        return None

    # ============================================================================
    # Constant and term visitors
    # ============================================================================

    def visitConstant(self, ctx: FormulaParser.ConstantContext):
        """Visit a constant (numeric or string)."""
        span = self.to_span(ctx)

        if ctx.str_():
            # String constant
            # TODO: Parse string properly
            text = ctx.getText()
            cnst = Cnst(span, text)
        else:
            # Numeric constant
            text = ctx.getText()
            is_fraction = ctx.FRAC() is not None
            cnst = self._parse_numeric(text, is_fraction, span)

        self._push_arg(cnst)
        return None

    def visitId(self, ctx: FormulaParser.IdContext):
        """Visit an identifier."""
        span = self.to_span(ctx)
        name = ctx.ID().getText()

        id_node = Id(span, name)
        self._push_arg(id_node)

        return None

    # ============================================================================
    # Helper methods
    # ============================================================================

    def _push_arg(self, node: Node):
        """Push an argument onto the argument stack."""
        self.arg_stack.append(node)

    def _pop_arg(self) -> Optional[Node]:
        """Pop an argument from the argument stack."""
        if self.arg_stack:
            return self.arg_stack.pop()
        return None

    def _parse_numeric(self, text: str, is_fraction: bool, span: Span) -> Cnst:
        """
        Parse a numeric constant.

        Args:
            text: The numeric text
            is_fraction: Whether this is a fraction (has '.')
            span: Source location

        Returns:
            Constant node
        """
        try:
            if is_fraction:
                # Parse as decimal and convert to rational
                # Handle formats like "3.14" or "0.5"
                parts = text.split('.')
                if len(parts) == 2:
                    # Convert decimal to fraction
                    numerator = int(parts[0] + parts[1])
                    denominator = 10 ** len(parts[1])
                    rational = Rational(numerator, denominator)
                else:
                    rational = Rational(int(text))
            else:
                # Integer
                rational = Rational(int(text))

            return Cnst(span, rational)
        except ValueError:
            # Invalid numeric format
            self.parse_result.add_flag(f"Invalid numeric constant: {text}")
            return Cnst(span, Rational(0))

    def _start_domain(self, name: str, kind: ComposeKind, span: Span):
        """Start building a domain."""
        assert self.current_module is None
        domain = Domain(span, name, kind)
        self.parse_result.program.add_module(domain)
        self.current_module = domain

    def _end_module(self):
        """End building a module."""
        assert self.current_module is not None
        self.current_module = None

    # ============================================================================
    # Default visitor (for unimplemented nodes)
    # ============================================================================

    def visitChildren(self, node):
        """
        Default visitor for nodes without specific handlers.

        This ensures we continue visiting children even for unimplemented nodes.
        """
        if node is None:
            return None

        result = None
        n = node.getChildCount()
        for i in range(n):
            child = node.getChild(i)
            if not self.shouldVisitNextChild(node, result):
                break
            child_result = child.accept(self)
            result = self.aggregateResult(result, child_result)

        return result

    def shouldVisitNextChild(self, node, current_result):
        """Check if we should visit the next child."""
        return True

    def aggregateResult(self, aggregate, next_result):
        """Aggregate results from visiting children."""
        return next_result
